from xmlrpc.server import SimpleXMLRPCServer
from xmlrpc.server import SimpleXMLRPCRequestHandler

def valor(x, y):
    if(y == "rgb"):
        rgb = {
        'amarelo':'FFFF00',
        'amarelo esverdeado':'99CC32',
        'aquamarine':'70DB93',
        'aquamarine médio':'32CD99',
        'azul':'0000FF',
        'azul ardósia':'007FFF',
        'azul ardósia escuro':'6B238E',
        'azul brilhante':'C0D9D9',
        'azul celeste':'3299CC',
        'azul claro':'5F9F9F',
        'azul corn flower':'42426F',
        'azul escuro':'00009C',
        'azul marinho':'23238E',
        'azul médio':'3232CD',
        'azul neon':'4D4DFF',
        'azul rich':'5959AB',
        'azul violeta':'9F5F9F',
        'bakers chocolate':'5C3317',
        'branco':'FFFFFF',
        'bright ouro':'D9D919',
        'bronze':'DB9370',
        'bronze claro':'EBC79E',
        'bronze escuro':'8C7853',
        'caqui':'9F9F5F',
        'cinza':'C0C0C0',
        'cinza brilhante':'A8A8A8',
        'cinza claro':'CDCDCD',
        'cobre':'D98719',
        'cobre claro':'B5A642',
        'cobre escuro':'B87333',
        'coral':'FF7F00',
        'cyan':'00FFFF',
        'escarlata':'8C1717',
        'firebrick':'8E2323',
        'goldenrod médio':'EAEAAE',
        'goldenrod':'DBDB70',
        'laranja':'FF7F00',
        'laranja mandarian':'E47833',
        'light steel blue':'8F8FBD',
        'light wood':'E9C2A6',
        'magenta':'FF00FF',
        'marrom':'8E236B',
        'marrom':'A62A2A',
        'marrom escuro':'5C4033',
        'medium slate blue':'7F00FF',
        'orquídea escuro':'9932CD',
        'orquídea médio':'9370DB',
        'ouro':'CD7F32',
        'ouro velho':'CFB53B',
        'plum':'EAADEA',
        'preto':'000000',
        'púrpura escuro':'871F78',
        'quartz':'D9D9F3',
        'rosa':'FF6EC7',
        'rosa temperado':'FF1CAE',
        'salmão':'6F4242',
        'semi-sweet chocolate':'6B4226',
        'sienna':'8E6B23',
        'silver':'E6E8FA',
        'steel azul':'236B8E',
        'summer sky':'38B0DE',
        'tan escuro':'97694F',
        'thistle':'D8BFD8',
        'turquesa':'ADEAEA',
        'turquesa escuro':'7093DB',
        'turquesa médio':'70DBDB',
        'verde':'00FF00',
        'verde amarelado':'93DB70',
        'verde cobre':'527F76',
        'verde cobre escuro':'4A766E',
        'verde escuro':'2F4F2F',
        'verde floresta':'238E23',
        'verde floresta médio':'6B8E23',
        'verde hunter':'215E21',
        'verde limão':'32CD32',
        'verde oceano':'426F42',
        'verde oceano claro':'238E68',
        'verde oliva escuro':'4F4F2F',
        'verde primavera':'7FFF00',
        'verde primavera':'00FF7F',
        'vermelho':'FF0000',
        'vermelho indiano':'4E2F2F',
        'vermelho violeta':'CC3299',
        'violeta':'4F2F4F',
        'violeta vermelho médio':'DB7093',
        'wheat':'D8D8BF',
        'wood médio':'A68064',
        }
        
        return rgb[x]

    if(y == "cor"):
        cores = {
        'FFFF00':'amarelo',
        '99CC32':'amarelo esverdeado',
        '70DB93':'aquamarine',
        '32CD99':'aquamarine médio',
        '0000FF':'azul',
        '007FFF':'azul ardósia',
        '6B238E':'azul ardósia escuro',
        'C0D9D9':'azul brilhante',
        '3299CC':'azul celeste',
        '5F9F9F':'azul claro',
        '42426F':'azul corn flower',
        '00009C':'azul escuro',
        '23238E':'azul marinho',
        '3232CD':'azul médio',
        '4D4DFF':'azul neon',
        '5959AB':'azul rich',
        '9F5F9F':'azul violeta',
        '5C3317':'bakers chocolate',
        'FFFFFF':'branco',
        'D9D919':'bright ouro',
        'DB9370':'bronze',
        'EBC79E':'bronze claro',
        '8C7853':'bronze escuro',
        '9F9F5F':'caqui',
        'C0C0C0':'cinza',
        'A8A8A8':'cinza brilhante',
        'CDCDCD':'cinza claro',
        'D98719':'cobre',
        'B5A642':'cobre claro',
        'B87333':'cobre escuro',
        'FF7F00':'coral',
        '00FFFF':'cyan',
        '8C1717':'escarlata',
        '8E2323':'firebrick',
        'EAEAAE':'goldenrod médio',
        'DBDB70':'goldenrod',
        'FF7F00':'laranja',
        'E47833':'laranja mandarian',
        '8F8FBD':'light steel blue',
        'E9C2A6':'light wood',
        'FF00FF':'magenta',
        '8E236B':'marrom',
        'A62A2A':'marrom',
        '5C4033':'marrom escuro',
        '7F00FF':'medium slate blue',
        '9932CD':'orquídea escuro',
        '9370DB':'orquídea médio',
        'CD7F32':'ouro',
        'CFB53B':'ouro velho',
        'EAADEA':'plum',
        '000000':'preto',
        '871F78':'púrpura escuro',
        'D9D9F3':'quartz',
        'FF6EC7':'rosa',
        'FF1CAE':'rosa temperado',
        '6F4242':'salmão',
        '6B4226':'semi-sweet chocolate',
        '8E6B23':'sienna',
        'E6E8FA':'silver',
        '236B8E':'steel azul',
        '38B0DE':'summer sky',
        '97694F':'tan escuro',
        'D8BFD8':'thistle',
        'ADEAEA':'turquesa',
        '7093DB':'turquesa escuro',
        '70DBDB':'turquesa médio',
        '00FF00':'verde',
        '93DB70':'verde amarelado',
        '527F76':'verde cobre',
        '4A766E':'verde cobre escuro',
        '2F4F2F':'verde escuro',
        '238E23':'verde floresta',
        '6B8E23':'verde floresta médio',
        '215E21':'verde hunter',
        '32CD32':'verde limão',
        '426F42':'verde oceano',
        '238E68':'verde oceano claro',
        '4F4F2F':'verde oliva escuro',
        '7FFF00':'verde primavera',
        '00FF7F':'verde primavera',
        'FF0000':'vermelho',
        '4E2F2F':'vermelho indiano',
        'CC3299':'vermelho violeta',
        '4F2F4F':'violeta',
        'DB7093':'violeta vermelho médio',
        'D8D8BF':'wheat',
        'A68064':'wood médio'
        }
        
        return cores[x]
    
    return 'Erro'

server = SimpleXMLRPCServer(("localhost", 8000))
print("Listening on port 8000...")
server.register_function(valor, 'valor')

server.serve_forever()